package cz.appsdevteam.gptom.models

object ResultCodes {
    const val OK = "ok"
    const val NOT_INITIALIZED = "notInitialized"
    const val NOT_INSTALLED = "notInstalled"
    const val UNSUPPORTED_ON_PLATFORM = "unsupportedOnPlatform"
    const val INVALID_ARGUMENT = "invalidArgument"
    const val TIMEOUT = "timeout"
    const val SERVICE_BIND_FAILED = "serviceBindFailed"
    const val INTERNAL_ERROR = "internalError"
    const val FAILED = "failed"
    const val NETWORK_ERROR = "networkError"
    const val INVALID_CLIENT_ID = "invalidClientId"
    const val MERCHANT_INFO_MISSING = "merchantInfoMissing"
    const val FAILED_TAP_TO_PAY = "failedTapToPay"
    const val FAILED_TO_CLOSE_BATCH = "failedToCloseBatch"
    const val INVALID_DEEPLINK = "invalidDeeplink"
    const val UNSUPPORTED_TRANSACTION_OPERATION_OR_TYPE = "unsupportedTransactionOperationOrType"
    const val INVALID_AMOUNT = "invalidAmount"
    const val CANNOT_BE_VOIDED = "cannotBeVoided"
    const val INVALID_CREDENTIALS = "invalidCredentials"
    const val TID_NOT_ASSIGNED_TO_THIS_USER = "tidNotAssignedToThisUser"
    const val TID_ALREADY_OCCUPIED = "tidAlreadyOccupied"
    const val ANOTHER_TID_USED_ON_THIS_DEVICE = "anotherTidUsedOnThisDevice"
    const val PASSWORD_CHANGE_REQUIRED = "passwordChangeRequired"
    const val PASSWORD_PENDING_CONFIRMATION = "passwordPendingConfirmation"
    const val INVALID_CODE = "invalidCode"
    const val INVALID_USER_NAME = "invalidUserName"
    const val TERMINAL_SETUP_FAILED = "terminalSetupFailed"
}
